### ISSUE TITLE
Logs of an update is not saved if the program crashes

### ISSUE THREAD

**Issue by xel1045** [EpicScriptTime/update-wrapper#11]
Example:

```
Updating index cache

Traceback (most recent call last):
  File "/usr/local/bin/update-wrapper", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/updatewrapper/__init__.py", line 88, in main
    wrap(hosts, out_dir, dist_upgrade)
  File "/usr/local/lib/python3.6/site-packages/updatewrapper/__init__.py", line 30, in wrap
    wrapper.update_cache()
  File "/usr/local/lib/python3.6/site-packages/updatewrapper/flavor/debian.py", line 16, in update_cache
    return self.host.run(ENV_VARS + 'apt-get update')
  File "/usr/local/lib/python3.6/site-packages/updatewrapper/host.py", line 34, in run
    return exec_command(self, cmd)
  File "/usr/local/lib/python3.6/site-packages/updatewrapper/command.py", line 28, in exec_command
    returncode, stdout, stderr = connection.exec_command(cmd, in_data=in_data, sudoable=sudoable)
  File "/usr/local/lib/python3.6/site-packages/updatewrapper/connection/ssh.py", line 689, in exec_command
    raise AnsibleConnectionFailure("Failed to connect to the host via ssh: %s" % to_native(return_tuple[2]))
ansible.errors.AnsibleConnectionFailure: Failed to connect to the host via ssh: eXolnet Inc.

This system is restricted to authorized access only. All activities on this
system are recorded and logged. Unauthorized access will be fully investigated
and reported to the appropriate law enforcement agencies.

Permission denied (publickey).
```

**Comment by xel1045** [comment]
Sorry, I was looking in the wrong directory.
